<?php
$usuario = $data['usuario'];
if (!is_array($usuario)) {
    $usuario = explode("|", $usuario);
}
?>
<form method="POST"
enctype="multipart/form-data">
    <ul>
        <li>
            <label>id</label>
            <input type="hidden" name="iduser" value="<?php echo $usuario[0];?>" />
        </li>
        <li>
            <label>Nombre</label>
            <input type="text" name="name" value="<?php echo $usuario[1];?>"/>
        </li>
        <li>
            <label>Email</label>
            <input type="email" name="email" value="<?php echo $usuario[2];?>"/>
        </li>
        <li>
            <label>Contraseña</label>
            <input type="password" name="password" />
        </li>
        <li>
            <label>Fecha de nacimiento</label>
            <input type="date" name="bdate" value="<?php echo $usuario[6];?>" />
        </li>
        <li>
            <label>Descripcion</label>
            <textarea rows="" cols="" name="description">
            <?php echo $usuario[4];?>
            </textarea>
        </li>
        <li>
            <label>Foto</label>
            <input type="file" name="photo" />
        </li>
        <li>
            <label>Privacidad</label>
            Sí<input type="checkbox" name="privacy[]" value="si" <?php if(in_array('si', [])) echo 'checked';?>/>
            Spam<input type="checkbox" name="privacy[]" value="spam" <?=(in_array('spam', []))?'checked':'';?>/>
        </li>
        <li>
            <label>Sexo</label>
            M<input type="radio" name="genders_idgender" value="1" <?=($usuario[7]=='1')?'checked':'';?> />
            H<input type="radio" name="genders_idgender" value="2" <?=($usuario[7]=='2')?'checked':'';?> />
            O<input type="radio" name="genders_idgender" value="3" <?=($usuario[7]=='3')?'checked':'';?> />            
        </li>
        <li>
            <label>Ciudad</label>
            <select name="cities_idcity">
                <option value="1" <?=([]=='Valencia')?'checked':'';?>>Valencia</option>
                <option value="2" <?=([]=='BCN')?'checked':'';?>>Barcelona</option>
                <option value="3" <?=([]=='Madrid')?'checked':'';?>>Madrid</option>
            </select>
        </li>
        
        <li>
            <label>Aficiones</label>
            <select multiple name="hobbies[]">
                <option <?=(in_array('Cine', []))?'selected':'';?>>Cine</option>
                <option <?=(in_array('Deporte', []))?'selected':'';?>>Deporte</option>
                <option <?=(in_array('Viajes', []))?'selected':'';?>>Viajes</option>                
            </select>
        </li>
        <li>
            <label>Enviar</label>
            <input type="submit" name="submit" />
        </li>
    </ul>
</form>

