<?php 
$usuarios = $data['usuarios'];
foreach ($usuarios as $user)
{
    $user = implode("|", $user);
    $rows[]=$user;
}
$usuarios=$rows;
?>
<a href="/users/insert">Insert</a>
<table  class="table table-striped">
<?php foreach ($usuarios as $key => $usuario):
    $usuario = explode("|", $usuario);
?>
    <tr>
        <?php foreach ($usuario as $key2 => $data):?>
            <td> <?=$data;?> </td>
        <?php endforeach;?>
        <td>
            <a href="/users/update/id/<?=$usuario[0];?>">Update</a> | 
            <a href="/users/delete/id/<?=$usuario[0];?>">Delete</a>
        </td>
    </tr>
<?php endforeach;?>
</table>